# Generated by Django 5.2.16 on 2026-07-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_schema_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
